### ISSUE TITLE
Auto Update Error on macOS

### ISSUE THREAD

**Issue by carrythebanner** [ThePacielloGroup/CCAe#204]
**Describe the bug**
When automatically checking for updates on macOS, an error is returned.

**Desktop (please complete the following information):**
 - OS: macOS v10.15.7, Intel Mac
 - Version: CCA 3.1.2

**To Reproduce**
1. Launch CCA on macOS 
2. Open Preferences and turn on the "Enable Auto Update" setting 
3. When the auto-update check runs, an error modal is displayed. The only choice is "OK" to dismiss the dialog. 

```
Error: Cannot find latest-mac.yml in the latest release artifacts (https://github.com/ThePacielloGroup/CCAe/releases/download/v3.1.3/latest-mac.yml): HttpError: 404 
"method: undefined url: https://github.com/ThePacielloGroup/CCAe/releases/download/v3.1.3/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "status": "404",
  "server": "GitHub.com",
  "date": "Fri, 02 Apr 2021 23:39:47 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "D247:808A:59D208:6561A5:6067AB43"
}
    at createHttpError (/Applications/Colour Contrast Analyser (CCA).app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at ElectronHttpExecutor.handleResponse (/Applications/Colour Contrast Analyser (CCA).app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:129:14)
    at ClientRequest.<anonymous> (/Applications/Colour Contrast Analyser (CCA).app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:85:16)
    at ClientRequest.emit (events.js:223:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6152)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
From previous event:
    at GitHubProvider.getLatestVersion (/Applications/Colour Contrast Analyser (CCA).app/Contents/Resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:39:25)
    at /Applications/Colour Contrast Analyser (CCA).app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:343:26
From previous event:
    at MacUpdater.getUpdateInfoAndProvider (/Applications/Colour Contrast Analyser (CCA).app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:332:43)
    at /Applications/Colour Contrast Analyser (CCA).app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:357:31
``` 

**Expected behavior**
Version check completes without error. 

**Screenshots**
![Auto Update Error](https://user-images.githubusercontent.com/29416700/113461900-6792f980-93d3-11eb-9af5-41c6671c587b.png)

**Additional context**
n/a

**Comment by ferllings** [comment]
I released a signed version for Windows, and I thought MacOS would ignore it because it doesn't have the upgrade manifest for MacOS... Obviously I was wrong.
Thnks
